default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("POSTGRES_HOST") { 'localhost' } %>
  user: postgres

development:
  <<: *default
  database: multitenancy_development

test:
  <<: *default
  database: multitenancy_test

production:
  <<: *default
  database: multitenancy_production
  username: gerente
  password: <%= ENV['MT_DATABASE_PASSWORD'] %>
